runtime: go122
service: default
instance_class: F1

env_variables:
  EXAMPLE_ENV: "production"
  DB_HOST: "/cloudsql/net1io-web-475001:asia-southeast2:gcp-site-db" # e.g., /cloudsql/my-gcp-project:us-central1:my-sql-instance
  DB_USER: "postgress"
  DB_PASSWORD: ""
  DB_NAME: "nmessage_db"