# NOTE: Automatic Cloud Build deployment encounters persistent App Engine internal errors.
# Using manual deployment workflow instead (see README.md for instructions).
#
# This file is kept for future reference when the issue is resolved.
#
# Steps attempted:
# - Granted all required permissions (appengine.deployer, appengine.appAdmin, storage.admin, iam.serviceAccountUser)
# - Tested with multiple service accounts (compute SA and cloudbuild SA)
# - Removed unused substitution variables
# - Files upload successfully but App Engine returns "Error Response: [13] An internal error occurred"
# - Manual deployment with same config works perfectly
#
# If you want to retry automatic deployment in the future, uncomment below:

# steps:
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         gcloud app deploy app.yaml \
#           --quiet \
#           --promote
#     timeout: '1200s'
#
# timeout: '1800s'
#
# options:
#   logging: LEGACY
#   machineType: 'E2_HIGHCPU_8'
