steps:
  # Step 1: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'
      - '--promote'
      - '--stop-previous-version'
    timeout: '1200s'

# Timeout for entire build
timeout: '1800s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitution variables (optional - can be used for branch-specific deployments)
substitutions:
  _SERVICE_NAME: 'default'
  _REGION: 'asia-southeast2'
